# Tg Bot default commands
start: # /start command; initial state
  text: |
    Welcome!
  buttons:
  - transition: hello
    label: Hello!

help: # /help command
  text: |
    Help

settings: # /settings command
  text: |
    Settings