# Tg Bot default commands
start: # /start command; initial state
  transition: waitlist

help: # /help command
  text: |
    Help
  transition: menu

settings: # /settings command
  text: |
    Settings
  transition: menu